/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e3e2e5", "primary-fixed": "#dfe3e7", "on-tertiary-fixed": "#121c2a",
        "tertiary-fixed": "#d9e3f7", background: "#121315", "on-primary-fixed": "#171c1f",
        "surface-variant": "#343537", "on-error": "#690005", secondary: "#e9c349",
        "tertiary-fixed-dim": "#bdc7da", "inverse-primary": "#5a5f62", "on-tertiary": "#273140",
        "tertiary-container": "#d9e3f7", "on-secondary-fixed-variant": "#574500",
        "surface-container-lowest": "#0d0e10", "primary-fixed-dim": "#c3c7cb",
        "surface-container-highest": "#343537", "secondary-fixed": "#ffe088",
        "on-error-container": "#ffdad6", "error-container": "#93000a", "on-secondary": "#3c2f00",
        primary: "#ffffff", "surface-tint": "#c3c7cb", "on-primary-container": "#606568",
        "surface-container": "#1f2022", "on-surface": "#e3e2e5", "on-primary": "#2c3134",
        outline: "#8e9194", "outline-variant": "#44474a", "surface-dim": "#121315",
        "surface-container-low": "#1b1c1e", error: "#ffb4ab", "on-background": "#e3e2e5",
        "on-primary-fixed-variant": "#43474b", "primary-container": "#dfe3e7",
        "surface-bright": "#38393b", "secondary-fixed-dim": "#e9c349",
        "on-surface-variant": "#c4c7c9", surface: "#121315", "secondary-container": "#af8d11",
        "surface-container-high": "#292a2c", "on-tertiary-fixed-variant": "#3d4757",
        "on-secondary-container": "#342800", tertiary: "#ffffff", "on-tertiary-container": "#5b6576",
        "inverse-on-surface": "#303033", "on-secondary-fixed": "#241a00",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "space-lg": "1.5rem", "space-xl": "3rem", "space-md": "1rem", gutter: "1.5rem",
        margin: "2.5rem", "space-xs": "0.25rem", "space-sm": "0.5rem",
      },
      fontFamily: {
        "body-sm": ["Inter"], display: ["Playfair Display"], "display-mobile": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"], "label-lg": ["Montserrat"],
        "headline-md": ["Playfair Display"], "headline-sm": ["Playfair Display"],
        "body-md": ["Inter"], "headline-lg": ["Playfair Display"], "body-lg": ["Inter"],
        "label-md": ["Montserrat"], "label-sm": ["Montserrat"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "400" }],
        display: ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.18em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0.01em", fontWeight: "300" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.22em", fontWeight: "500" }],
        "label-sm": ["9px", { lineHeight: "14px", letterSpacing: "0.28em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};